### ISSUE TITLE
Feature request: support Carthage

### ISSUE THREAD

**Issue by antonys1** [RobotsAndPencils/Astro#14]
https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

**Comment by interstateone** [comment]
Hi @antonys1, thanks for checking out Astro! Carthage isn't a tool we use a lot on our team at the moment but I don't see any harm in supporting Carthage if there was a strong demand for it and doesn't require maintenance for us. I checked the link you added and based on the requirements (shared schemes and git tags for releases) it seems like this library will already support Carthage. If you have any issues please submit a pull request so others can take advantage of your changes as well. Thanks!
